modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="universal"
version="0.0.1-1.19"
displayName="Universal Mod"
logoFile=""
credits=""
authors="Albert_1403"
description='''

'''
[[dependencies.universal]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.universal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
